"""'migrate'

Revision ID: 053ef46995b4
Revises: e205bbf4cf5d
Create Date: 2021-08-31 04:49:18.035719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053ef46995b4'
down_revision = 'e205bbf4cf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
