"""'migrate'

Revision ID: 10ee33df8268
Revises: 6a69fffe9213
Create Date: 2021-08-31 18:59:17.742056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ee33df8268'
down_revision = '6a69fffe9213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
