"""your migration description

Revision ID: 25781b88b9dc
Revises: c6290b11f7f2
Create Date: 2021-09-01 03:12:25.810841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25781b88b9dc'
down_revision = 'c6290b11f7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
