"""your migration description

Revision ID: 38b2cd91582d
Revises: 8442b86a3e11
Create Date: 2021-09-01 03:17:05.368904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b2cd91582d'
down_revision = '8442b86a3e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
