"""migrate

Revision ID: 6a69fffe9213
Revises: 79a8df08387b
Create Date: 2021-08-31 18:58:45.578619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a69fffe9213'
down_revision = '79a8df08387b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
