"""your migration description

Revision ID: 6bec64274e4a
Revises: a90688b17f9e
Create Date: 2021-08-31 04:34:20.862293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec64274e4a'
down_revision = 'a90688b17f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
