"""your migration description

Revision ID: 704700e843b3
Revises: cd250661a3f0
Create Date: 2021-09-01 03:10:18.170329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704700e843b3'
down_revision = 'cd250661a3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
