"""your migration description

Revision ID: 79a8df08387b
Revises: 053ef46995b4
Create Date: 2021-08-31 18:57:58.937611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a8df08387b'
down_revision = '053ef46995b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
