"""your migration description

Revision ID: 8442b86a3e11
Revises: e9bb1cf8e6f3
Create Date: 2021-09-01 03:14:55.941886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8442b86a3e11'
down_revision = 'e9bb1cf8e6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
