"""first migration

Revision ID: a4a8fb3dc42e
Revises: df151fd67824
Create Date: 2021-08-31 04:33:31.240414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a8fb3dc42e'
down_revision = 'df151fd67824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
