"""your migration description

Revision ID: a90688b17f9e
Revises: a4a8fb3dc42e
Create Date: 2021-08-31 04:34:15.003954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90688b17f9e'
down_revision = 'a4a8fb3dc42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
