"""your migration description

Revision ID: ae3ad1affa55
Revises: c589fa239253
Create Date: 2021-08-31 04:31:18.373936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3ad1affa55'
down_revision = 'c589fa239253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
