"""first migration

Revision ID: c6290b11f7f2
Revises: 704700e843b3
Create Date: 2021-09-01 03:12:05.918700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6290b11f7f2'
down_revision = '704700e843b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
