"""your migration description

Revision ID: cadadf4c4068
Revises: 25781b88b9dc
Create Date: 2021-09-01 03:12:48.201423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadadf4c4068'
down_revision = '25781b88b9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
