"""your migration description

Revision ID: d59a544e0a3a
Revises: 38b2cd91582d
Create Date: 2021-09-01 18:01:41.292500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59a544e0a3a'
down_revision = '38b2cd91582d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
