"""your migration description

Revision ID: df151fd67824
Revises: ae3ad1affa55
Create Date: 2021-08-31 04:32:01.339176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df151fd67824'
down_revision = 'ae3ad1affa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
