"""your migration description

Revision ID: e205bbf4cf5d
Revises: eb10b52a45ad
Create Date: 2021-08-31 04:45:05.637926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e205bbf4cf5d'
down_revision = 'eb10b52a45ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
