"""your migration description

Revision ID: e9bb1cf8e6f3
Revises: cadadf4c4068
Create Date: 2021-09-01 03:14:16.200592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bb1cf8e6f3'
down_revision = 'cadadf4c4068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
