"""your migration description

Revision ID: eb10b52a45ad
Revises: f2c4d41ce1db
Create Date: 2021-08-31 04:43:48.683033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb10b52a45ad'
down_revision = 'f2c4d41ce1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tags',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'timer',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timer',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'tags',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
