"""your migration description

Revision ID: f2c4d41ce1db
Revises: f5452d974477
Create Date: 2021-08-31 04:43:04.644771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c4d41ce1db'
down_revision = 'f5452d974477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
