"""first migration

Revision ID: f5452d974477
Revises: 4a254a8f391a
Create Date: 2021-08-31 04:42:46.614377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5452d974477'
down_revision = '4a254a8f391a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
